apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  # These are placeholder values - override in overlays or use external secrets
  POSTGRES_DB: polaris
  POSTGRES_USER: polaris
  POSTGRES_PASSWORD: changeme
